version: '3.0'
services:
  docker-mc:
    build: ./
    image: docker-mc
    container_name: docker-mc
    working_dir: /opt/app
    ports:
      - "3000:3000"
      - "127.0.0.1:3001:3000"
    environment: 
      - APPLICATION_NAME=Some awesome application
    volumes:
      - ./app:/opt/app
    networks:
      - dmc-network
    depends_on:
      - docker-mc-db
  docker-mc-db:
    image: postgres:11-alpine
    restart: "no"
    container_name: docker-mc-db
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pgdb
      POSTGRES_USER: pguser
    ports:
      - "5432:5432"
    networks:
      - dmc-network
networks:
  dmc-network:
    driver: bridge
      