version: '3.0'
services:
  docker-mc-ngx:
    image: nginx:1.18-alpine
    container_name: docker-mc-ngx
    depends_on:
      - docker-mc
      - docker-mc-2
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/
    networks:
      - dmc-network
  docker-mc:
    build: ./
    image: docker-mc
    container_name: docker-mc
    working_dir: /opt/app
    expose:
      - "3000"
    environment: 
      - APPLICATION_NAME=Some awesome application
    volumes:
      - ./app:/opt/app
    networks:
      - dmc-network
    depends_on:
      - docker-mc-db
  docker-mc-2:
    build: ./
    image: docker-mc-2
    container_name: docker-mc-2
    working_dir: /opt/app
    expose:
      - "3000"
    environment: 
      - APPLICATION_NAME=Another awesome application
    volumes:
      - ./app:/opt/app
    networks:
      - dmc-network
    depends_on:
      - docker-mc-db
  docker-mc-db:
    image: postgres:11-alpine
    restart: "no"
    container_name: docker-mc-db
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pgdb
      POSTGRES_USER: pguser
    ports:
      - "5432:5432"
    networks:
      - dmc-network
networks:
  dmc-network:
    driver: bridge
      